name: Release workflow

permissions:
  contents: write

on:
  push:
    tags: "*"

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v2
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      max-parallel: 1
      matrix:
        arch:
          - amd64
          - arm64
        php_version:
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/${{ matrix.arch }}
      - name: Build nop_${{ matrix.arch }}_${{ matrix.php_version }}.so.out
        run: |
          docker run \
            --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            --platform linux/${{ matrix.arch }} \
            php:${{ matrix.php_version }}-cli \
            ./scripts/build-extension
      - name: Generate nfpm.${{ matrix.arch }}.${{ matrix.php_version }}.yaml
        run: ./scripts/nfpm-template
        env:
          VERSION: ${{ github.ref_name }}
          ARCH: ${{ matrix.arch }}
          PHP_VERSION: ${{ matrix.php_version }}
      - name: Package php${{ matrix.php_version }}-nop_${{ matrix.arch }}_${{ github.ref_name }}.deb
        run: |
          docker run \
            --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            --platform linux/${{ matrix.arch }} \
            goreleaser/nfpm:v2.41.0 \
            pkg \
              --packager deb \
              --config nfpm.${{ matrix.arch }}.${{ matrix.php_version }}.yaml \
              --target ./private/php${{ matrix.php_version }}-nop_${{ matrix.arch }}_${{ github.ref_name }}.deb
      - name: Upload php${{ matrix.php_version }}-nop_${{ matrix.arch }}_${{ github.ref_name }}.deb
        id: upload-release-asset 
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./private/php${{ matrix.php_version }}-nop_${{ matrix.arch }}_${{ github.ref_name }}.deb
